#define ROF_SINGLE "SINGLE"
#define ROF_BURST "BURST"
#define ROF_FULL_AUTO "FULL-AUTO"

#define SENTRY_CATEGORY_IFF "IFF STATUS"
#define SENTRY_CATEGORY_ROF "RATE OF FIRE"

#define SENTRY_IFF_OFF "DISABLE"
#define SENTRY_IFF_HALF "ONLY PRIMARY FACTION"
#define SENTRY_IFF_FULL "FULL"
